version: '3.3'
services:
    redis:
        image: 'redis:latest'
        container_name: redis
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        networks:
            - myNetwork
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/redis/data
        restart: always
    db:
        image: 'mongo:latest'
        container_name: db
        ports:
            - '27017:27017'
        restart: always
        environment:
            MONGODB_ADMIN_USER: ${DATABASE_USERNAME}
            MONGODB_ADMIN_PASS: ${DATABASE_PASSWORD}
            MONGODB_DATABASE: ${DATABASE_DB_NAME}
        volumes:
            - db_data:/var/lib/mongo
        networks:
            - myNetwork
        command: mongod
    project:
        build:
            context: .
            dockerfile: Dockerfile
        image: project
        container_name: project
        networks:
            - myNetwork
        ports:
            - '8080:8080'
        volumes:
            - './public:/home/project/public'
        restart: always
        depends_on:
            - redis
            - db
        environment:
            - DATABASE_HOST=db
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PREFIX=${REDIS_PREFIX}

networks:
    myNetwork:

volumes:
    redis_data:
    db_data:
